use_frameworks!

platform :ios, '9.0'

target 'ShawVideoProcessing_Example' do
  pod 'ShawVideoProcessing', :path => '../'

  target 'ShawVideoProcessing_Tests' do
    inherit! :search_paths

    
  end
end
